export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_ERR = 'CREATE_POST_ERR';

export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_ERR = 'DELETE_POST_ERR';

export const SHOW_POST = 'SHOW_POST';
export const SHOW_POST_ERR = 'SHOW_POST_ERR';

export const FETCH_POSTS_INIT = 'FETCH_POSTS_INIT';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILED = 'FETCH_POSTS_FAILED';
